#config_version=6

mode:
  start_events: ball_starting
  stop_events: stop_mode_arrow_targets, ball_will_end
  priority: 300

shot_profiles:
  arrow_target_profile:
    states:
      - name:
        show: off
        speed: 10
      - name: hit
        show: on

shot_groups:
  arrow_target_group:
    shots: arrow_target_1, arrow_target_2, arrow_target_3, arrow_target_4, arrow_target_5, arrow_target_6
    reset_events: arrow_target_group_hit_complete

shots:
  arrow_target_1:
    switch: s_arrow_1    
    profile: arrow_target_profile
    show_tokens:
      led: l_arrow_1
  arrow_target_2:
    switch: s_arrow_2    
    profile: arrow_target_profile
    show_tokens:
      led: l_arrow_2
  arrow_target_3:
    switch: s_arrow_3    
    profile: arrow_target_profile
    show_tokens:
      led: l_arrow_3
  arrow_target_4:
    switch: s_arrow_4    
    profile: arrow_target_profile
    show_tokens:
      led: l_arrow_4
  arrow_target_5:
    switch: s_arrow_5    
    profile: arrow_target_profile
    show_tokens:
      led: l_arrow_5
  arrow_target_6:
    switch: s_arrow_6   
    profile: arrow_target_profile
    show_tokens:
      led: l_arrow_6