hardware:
  platform: fast
  driverboards:
    - fast:io-1
    - fast:io-2
  leds:
    - fast:exp-48
    - fast:exp-b4

balls_installed: 3

switches:
  trough_ball_3:
    number: fast:io-2-41
    type: NO
    tags: trough
  left_upper_bumper:
    number: fast:io-1-2
    type: NO
    tags: target
  left_center_bumper:
    number: fast:io-1-3
    type: NO
    tags: target
  lock_1_(left):
    number: fast:io-1-4
    type: NO
    tags: lock
  left_lower_bumper:
    number: fast:io-1-5
    type: NO
    tags: target
  star_1_(left):
    number: fast:io-1-6
    type: NO
    tags: rollover
  shooter_trough:
    number: fast:io-1-7
    type: NO
    tags: shooter_lane
  left_out_lane_/_"sheild":
    number: fast:io-1-8
    type: NO
    tags: playfield
  left_return_lane:
    number: fast:io-1-9
    type: NO
    tags: playfield
  left_slingshot:
    number: fast:io-1-10
    type: NO
    tags: target
  left_flipper_eos:
    number: fast:io-1-11
    type: NO
    tags: EOS
  outhole:
    number: fast:io-1-12
    type: NO
    tags: drain
  lane_"f":
    number: fast:io-1-16
    type: NO
    tags: playfield
  lane_"i":
    number: fast:io-1-17
    type: NO
    tags: playfield
  lane_"r":
    number: fast:io-1-18
    type: NO
    tags: playfield
  lane_"e":
    number: fast:io-1-19
    type: NO
    tags: playfield
  lock_3_(top):
    number: fast:io-1-20
    type: NO
    tags: lock
  lock_2_(right):
    number: fast:io-1-21
    type: NO
    tags: lock
  arrow_"6":
    number: fast:io-1-24
    type: NO
    tags: target
  arrow_"5":
    number: fast:io-1-25
    type: NO
    tags: target
  arrow_"4":
    number: fast:io-1-26
    type: NO
    tags: target
  star_2_(right):
    number: fast:io-1-27
    type: NO
    tags: playfield
  pop_bumper_2:
    number: fast:io-1-28
    type: NO
    tags: pop_bumper
  pop_bumper_4:
    number: fast:io-1-29
    type: NO
    tags: pop_bumper
  pop_bumper_1:
    number: fast:io-1-30
    type: NO
    tags: pop_bumper
  pop_bumper_3:
    number: fast:io-1-31
    type: NO
    tags: pop_bumper
  right_upper_bumper:
    number: fast:io-2-32
    type: NO
    tags: target
  power_1:
    number: fast:io-2-33
    type: NO
    tags: target
  power_2:
    number: fast:io-2-34
    type: NO
    tags: target
  power_3:
    number: fast:io-2-35
    type: NO
    tags: target
  right_lower_bumper:
    number: fast:io-2-36
    type: NO
    tags: target
  right_slingshot:
    number: fast:io-2-37
    type: NO
    tags: slingshot
  right_out_lane:
    number: fast:io-2-38
    type: NO
    tags: playfield
  right_return_lane:
    number: fast:io-2-39
    type: NO
    tags: playfield
  trough_ball_1:
    number: fast:io-2-40
    type: NO
    tags: trough
  trough_ball_2:
    number: fast:io-2-42
    type: NO
    tags: trough
  right_flipper_eos:
    number: fast:io-2-43
    type: NO
    tags: eos
  arrow_"3":
    number: fast:io-2-44
    type: NO
    tags: target
  arrow_"2":
    number: fast:io-2-45
    type: NO
    tags: target
  arrow_"1":
    number: fast:io-2-46
    type: NO
    tags: target
  start_button:
    number: fast:io-2-56
    type: NO
    tags: Start
  left_flipper:
    number: fast:io-2-57
    type: NO
    tags: flipper
  right_flipper:
    number: fast:io-2-65
    type: NO
    tags: flipper

coils:
  shield_kicker:
    number: fast:io-1-0
    default_pulse_ms: 20
  left_flipper:
    number: fast:io-1-1
    default_pulse_ms: 20
  left_flipper_hold:
    number: fast:io-1-2
    hold_power: 0.20
  left_slingshot:
    number: fast:io-1-3
    default_pulse_ms: 20
  lock_1_eject:
    number: fast:io-1-4
    default_pulse_ms: 20
  pop_bumper_2:
    number: fast:io-1-5
    default_pulse_ms: 20
  pop_bumper_1:
    number: fast:io-1-6
    default_pulse_ms: 20
  pop_bumper_3:
    number: fast:io-1-7
    default_pulse_ms: 20
  pop_bumper_4:
    number: fast:io-1-23
    default_pulse_ms: 20
  outhole_eject:
    number: fast:io-1-16
    default_pulse_ms: 20
  ball_trough_eject:
    number: fast:io-1-17
    default_pulse_ms: 20
  right_flipper:
    number: fast:io-1-18
    default_pulse_ms: 20
  right_flipper_hold:
    number: fast:io-1-19
    hold_power: 0.20
  right_slingshot:
    number: fast:io-1-20
    default_pulse_ms: 20
  lock_2_eject:
    number: fast:io-1-21
    default_pulse_ms: 20
  lock_3_eject:
    number: fast:io-1-22
    default_pulse_ms: 20

flippers:
  left_flipper:
    type: main/hold
    switch: left_flipper
    eos_switch: eos_switch_placeholder
    main_coil: left_flipper
    hold_coil: left_flipper_hold
    allow_enable: true
  right_flipper:
    type: main/hold
    switch: right_flipper
    eos_switch: eos_switch_placeholder
    main_coil: right_flipper
    hold_coil: right_flipper_hold
    allow_enable: true

autofire_coils:
  left_slingshot:
    coil: left_slingshot
    switch: left_slingshot
    cooldown_ms: 50
  pop_bumper_2:
    coil: pop_bumper_2
    switch: pop_bumper_1
    cooldown_ms: 50
  pop_bumper_1:
    coil: pop_bumper_1
    switch: pop_bumper_2
    cooldown_ms: 50
  pop_bumper_3:
    coil: pop_bumper_3
    switch: pop_bumper_3
    cooldown_ms: 50
  pop_bumper_4:
    coil: pop_bumper_4
    switch: pop_bumper_4
    cooldown_ms: 50
  right_slingshot:
    coil: right_slingshot
    switch: right_slingshot
    cooldown_ms: 50

lights:
  player_1_score_indicator:
    number: fast:exp-48-0.0
    subtype: rgb
    color_correction_profile: fast_grb
  high_score_indicator:
    number: fast:exp-48-1.0
    subtype: rgb
    color_correction_profile: fast_grb
  player_2_score_indicator:
    number: fast:exp-48-2.0
    subtype: rgb
    color_correction_profile: fast_grb
  player_3_score_indicator:
    number: fast:exp-48-3.0
    subtype: rgb
    color_correction_profile: fast_grb
  player_4_score_indicator:
    number: fast:exp-48-4.0
    subtype: rgb
    color_correction_profile: fast_grb
  tilt:
    number: fast:exp-48-5.0
    subtype: rgb
    color_correction_profile: fast_grb
  player_4_indicator:
    number: fast:exp-48-6.0
    subtype: rgb
    color_correction_profile: fast_grb
  player_3_indicator:
    number: fast:exp-48-7.0
    subtype: rgb
    color_correction_profile: fast_grb
  player_2_indicator:
    number: fast:exp-48-8.0
    subtype: rgb
    color_correction_profile: fast_grb
  player_1_indicator:
    number: fast:exp-48-9.0
    subtype: rgb
    color_correction_profile: fast_grb
  "fire_again!!":
    number: fast:exp-48-nan
    subtype: rgb
    color_correction_profile: fast_grb
  "match":
    number: fast:exp-48-12.0
    subtype: rgb
    color_correction_profile: fast_grb
  "ball_in_play":
    number: fast:exp-48-13.0
    subtype: rgb
    color_correction_profile: fast_grb
  "game_over":
    number: fast:exp-48-nan
    subtype: rgb
    color_correction_profile: fast_grb
  "fire"_lane_1000_when_lit:
    number: fast:exp-b4-0.0
    subtype: rgb
    color_correction_profile: fast_rgb
  lock_1_(left)_star_rollover:
    number: fast:exp-b4-1.0
    subtype: rgb
    color_correction_profile: fast_rgb
  lock_1_"lock"_arrow:
    number: fast:exp-b4-2.0
    subtype: rgb
    color_correction_profile: fast_rgb
  shield_on_when_lit:
    number: fast:exp-b4-3.0
    subtype: rgb
    color_correction_profile: fast_rgb
  left_ball_return_lane_3000_when_lit:
    number: fast:exp-b4-4.0
    subtype: rgb
    color_correction_profile: fast_rgb
  left_outlane_"special":
    number: fast:exp-b4-5.0
    subtype: rgb
    color_correction_profile: fast_rgb
  left_outlane_illumination_left:
    number: fast:exp-b4-6.0
    subtype: rgb
    color_correction_profile: fast_grb
  left_outlane_illumination_right:
    number: fast:exp-b4-7.0
    subtype: rgb
    color_correction_profile: fast_grb
  "2x"_bonus_multiplier:
    number: fast:exp-b4-8.0
    subtype: rgb
    color_correction_profile: fast_rgb
  "3x"_bonus_multiplier:
    number: fast:exp-b4-9.0
    subtype: rgb
    color_correction_profile: fast_rgb
  "fire"_lamp_3:
    number: fast:exp-b4-10.0
    subtype: rgb
    color_correction_profile: fast_grb
  "fire"_lamp_2:
    number: fast:exp-b4-11.0
    subtype: rgb
    color_correction_profile: fast_grb
  "fire"_lamp_1:
    number: fast:exp-b4-12.0
    subtype: rgb
    color_correction_profile: fast_grb
  arrow_"1":
    number: fast:exp-b4-32.0
    subtype: rgb
    color_correction_profile: fast_rgb
  arrow_"2":
    number: fast:exp-b4-33.0
    subtype: rgb
    color_correction_profile: fast_rgb
  arrow_"3":
    number: fast:exp-b4-34.0
    subtype: rgb
    color_correction_profile: fast_rgb
  arrow_"4":
    number: fast:exp-b4-35.0
    subtype: rgb
    color_correction_profile: fast_rgb
  arrow_"5":
    number: fast:exp-b4-36.0
    subtype: rgb
    color_correction_profile: fast_rgb
  arrow_"6":
    number: fast:exp-b4-37.0
    subtype: rgb
    color_correction_profile: fast_rgb
  bonus_"20":
    number: fast:exp-b4-38.0
    subtype: rgb
    color_correction_profile: fast_rgb
  bonus_"10":
    number: fast:exp-b4-39.0
    subtype: rgb
    color_correction_profile: fast_rgb
  bonus_"9":
    number: fast:exp-b4-40.0
    subtype: rgb
    color_correction_profile: fast_rgb
  bonus_"8":
    number: fast:exp-b4-41.0
    subtype: rgb
    color_correction_profile: fast_rgb
  bonus_"7":
    number: fast:exp-b4-42.0
    subtype: rgb
    color_correction_profile: fast_rgb
  bonus_"6":
    number: fast:exp-b4-43.0
    subtype: rgb
    color_correction_profile: fast_rgb
  bonus_"5":
    number: fast:exp-b4-44.0
    subtype: rgb
    color_correction_profile: fast_rgb
  bonus_"4":
    number: fast:exp-b4-45.0
    subtype: rgb
    color_correction_profile: fast_rgb
  bonus_"3":
    number: fast:exp-b4-46.0
    subtype: rgb
    color_correction_profile: fast_rgb
  bonus_"2":
    number: fast:exp-b4-47.0
    subtype: rgb
    color_correction_profile: fast_rgb
  bonus_"1":
    number: fast:exp-b4-48.0
    subtype: rgb
    color_correction_profile: fast_rgb
  "fire_again":
    number: fast:exp-b4-49.0
    subtype: rgb
    color_correction_profile: fast_rgb
  lock_2_(right)_star_rollover:
    number: fast:exp-b4-64.0
    subtype: rgb
    color_correction_profile: fast_rgb
  lock_2_"lock"_arrow:
    number: fast:exp-b4-65.0
    subtype: rgb
    color_correction_profile: fast_rgb
  right_target_indicator_1:
    number: fast:exp-b4-66.0
    subtype: rgb
    color_correction_profile: fast_rgb
  right_target_indicator_2:
    number: fast:exp-b4-67.0
    subtype: rgb
    color_correction_profile: fast_rgb
  right_target_indicator_3:
    number: fast:exp-b4-68.0
    subtype: rgb
    color_correction_profile: fast_rgb
  extra_ball_arrow:
    number: fast:exp-b4-69.0
    subtype: rgb
    color_correction_profile: fast_rgb
  right_outlane_"special":
    number: fast:exp-b4-70.0
    subtype: rgb
    color_correction_profile: fast_rgb
  right_return_lane_100_when_lit:
    number: fast:exp-b4-71.0
    subtype: rgb
    color_correction_profile: fast_rgb
  "power"_lamp_3:
    number: fast:exp-b4-72.0
    subtype: rgb
    color_correction_profile: fast_grb
  "power"_lamp_2:
    number: fast:exp-b4-73.0
    subtype: rgb
    color_correction_profile: fast_grb
  "power"_lamp_1:
    number: fast:exp-b4-74.0
    subtype: rgb
    color_correction_profile: fast_grb
  right_outlane_illumination_left:
    number: fast:exp-b4-75.0
    subtype: rgb
    color_correction_profile: fast_grb
  right_outlane_illumination_right:
    number: fast:exp-b4-76.0
    subtype: rgb
    color_correction_profile: fast_grb
  "5x"_bonus_multiplier:
    number: fast:exp-b4-77.0
    subtype: rgb
    color_correction_profile: fast_rgb
  "4x"_bonus_multiplier:
    number: fast:exp-b4-78.0
    subtype: rgb
    color_correction_profile: fast_rgb
  "f":
    number: fast:exp-b4-96.0
    subtype: rgb
    color_correction_profile: fast_rgb
  lock_3_(top)_arrow:
    number: fast:exp-b4-97.0
    subtype: rgb
    color_correction_profile: fast_rgb
  "i":
    number: fast:exp-b4-98.0
    subtype: rgb
    color_correction_profile: fast_rgb
  "r":
    number: fast:exp-b4-99.0
    subtype: rgb
    color_correction_profile: fast_rgb
  "e":
    number: fast:exp-b4-100.0
    subtype: rgb
    color_correction_profile: fast_rgb
  "fire"_lane_guide_4:
    number: fast:exp-b4-101.0
    subtype: rgb
    color_correction_profile: fast_grb
  "fire"_lane_guide_3:
    number: fast:exp-b4-102.0
    subtype: rgb
    color_correction_profile: fast_grb
  "target_scores_1000":
    number: fast:exp-b4-103.0
    subtype: rgb
    color_correction_profile: fast_rgb
  "fire"_lane_guide_2:
    number: fast:exp-b4-104.0
    subtype: rgb
    color_correction_profile: fast_grb
  "fire"_lane_guide_1:
    number: fast:exp-b4-105.0
    subtype: rgb
    color_correction_profile: fast_grb
  target_score_10,000:
    number: fast:exp-b4-106.0
    subtype: rgb
    color_correction_profile: fast_rgb
  target_score_30,000:
    number: fast:exp-b4-107.0
    subtype: rgb
    color_correction_profile: fast_rgb
  target_score_50,000:
    number: fast:exp-b4-108.0
    subtype: rgb
    color_correction_profile: fast_rgb
  nan:
    number: fast:exp-b4-nan
    subtype: rgb
    color_correction_profile: fast_rgb
  nan:
    number: fast:exp-b4-nan
    subtype: rgb
    color_correction_profile: fast_rgb
  nan:
    number: fast:exp-b4-nan
    subtype: rgb
    color_correction_profile: fast_rgb
  nan:
    number: fast:exp-b4-nan
    subtype: rgb
    color_correction_profile: fast_rgb