#config_version=6

mode:
  start_events: ball_starting
  stop_events: ball_ended, game_ended
  priority: 350

event_player:
  fire_power_lit{current_player.firepower_bonus_level==1}: collect_firepower_bonus_10000
  fire_power_lit{current_player.firepower_bonus_level==2}: collect_firepower_bonus_30000
  fire_power_lit{current_player.firepower_bonus_level==3}: collect_firepower_bonus_50000
  fire_power_lit{current_player.firepower_bonus_level>=4}: light_outlane_specials

  mode_firepower_bonus_started{current_player.firepower_bonus_level==1}: restore_firepower_bonus_10000
  mode_firepower_bonus_started{current_player.firepower_bonus_level==2}: restore_firepower_bonus_30000
  mode_firepower_bonus_started{current_player.firepower_bonus_level==3}: restore_firepower_bonus_50000

  s_left_out_lane_active{current_player.special_lit==1}: collect_special
  s_right_out_lane_active{current_player.special_lit==1}: collect_special

show_player:
  collect_firepower_bonus_10000:
    firepower_bonus_awarded:
      action: play
      loops: 3
    firepower_bonus_10000_lit:
      action: stop
    firepower_bonus_30000_lit:
      action: play
      loops: -1

  collect_firepower_bonus_30000:
    firepower_bonus_awarded:
      action: play
      loops: 3
    firepower_bonus_30000_lit:
      action: stop
    firepower_bonus_50000_lit:
      action: play
      loops: -1

  collect_firepower_bonus_50000:
    firepower_bonus_awarded:
      action: play
      loops: 3
    firepower_bonus_50000_lit:
      action: stop

  light_outlane_specials:
    firepower_bonus_awarded:
      action: play
      loops: 3
    specials_lit_show:
      action: play
      loops: -1

  restore_firepower_bonus_10000:
    firepower_bonus_10000_lit:
      action: play
      loops: -1

  restore_firepower_bonus_30000:
    firepower_bonus_30000_lit:
      action: play
      loops: -1

  restore_firepower_bonus_50000:
    firepower_bonus_50000_lit:
      action: play
      loops: -1

  collect_special:
    specials_lit_show:
      action: stop

variable_player:
  collect_firepower_bonus_10000:
    score:
      int: 10000
      action: add
    firepower_bonus_level:
      int: 2
      action: set
    fire_lit:
      int: 0
      action: set
    power_lit:
      int: 0
      action: set

  collect_firepower_bonus_30000:
    score:
      int: 30000
      action: add
    firepower_bonus_level:
      int: 3
      action: set
    fire_lit:
      int: 0
      action: set
    power_lit:
      int: 0
      action: set

  collect_firepower_bonus_50000:
    score:
      int: 50000
      action: add
    firepower_bonus_level:
      int: 4
      action: set
    fire_lit:
      int: 0
      action: set
    power_lit:
      int: 0
      action: set

  light_outlane_specials:
    special_lit:
      int: 1
      action: set
    fire_lit:
      int: 0
      action: set
    power_lit:
      int: 0
      action: set

  collect_special:
    special_lit:
      int: 0
      action: set
    fire_lit:
      int: 0
      action: set
    power_lit:
      int: 0
      action: set
    firepower_bonus_level:
      int: 1
      action: set