#config_version=6

mode:
  start_events: ball_starting
  stop_events: ball_ended, game_ended
  priority: 350

event_player:
  fire_power_lit{current_player.firepower_bonus_level==1}: collect_firepower_bonus_10000
  fire_power_lit{current_player.firepower_bonus_level==2}: collect_firepower_bonus_30000
  fire_power_lit{current_player.firepower_bonus_level==3}: collect_firepower_bonus_50000
  fire_power_lit{current_player.firepower_bonus_level>=4}: light_outlane_specials

show_player:
  mode_firepower_bonus_started:
    firepower_bonus_10000_lit:
      action: play
      loops: -1

  collect_firepower_bonus_10000:
    firepower_bonus_10000_lit:
      action: stop
    firepower_bonus_30000_lit:
      action: play
      loops: -1

  collect_firepower_bonus_30000:
    firepower_bonus_30000_lit:
      action: stop
    firepower_bonus_50000_lit:
      action: play
      loops: -1

  collect_firepower_bonus_50000:
    firepower_bonus_50000_lit:
      action: stop

  light_outlane_specials:
    specials_lit_show:
      action: play
      loops: -1

variable_player:
  ball_started:
    firepower_bonus_level:
      int: 1
      action: set

  collect_firepower_bonus_10000:
    score: 10000
    firepower_bonus_level:
      int: 2
      action: set
    fire_lit:
      int: 0
      action: set
    power_lit:
      int: 0
      action: set

  collect_firepower_bonus_30000:
    score: 30000
    firepower_bonus_level:
      int: 3
      action: set
    fire_lit:
      int: 0
      action: set
    power_lit:
      int: 0
      action: set

  collect_firepower_bonus_50000:
    score: 50000
    firepower_bonus_level:
      int: 4
      action: set
    fire_lit:
      int: 0
      action: set
    power_lit:
      int: 0
      action: set

  light_outlane_specials:
    special_lit:
      int: 1
      action: set
    fire_lit:
      int: 0
      action: set
    power_lit:
      int: 0
      action: set