#config_version=6
modes:
  - base
  - bonus_collect
  - lock_qualification
  - firepower_bonus
  - firepower_multiball
  - jet_bumpers
  - lane_change
  - power_targets
  - segment_display
  - shield_qualifier
  - shield
  - spinner