#config_version=6

mode:
  start_events: ball_starting
  stop_events: game_ended
  priority: 325

multiball_locks:
  firepower_lock_1:
    lock_devices: bd_lock1
    balls_to_lock: 1
    balls_to_replace: 1
    enable_events: qualify_lock_1
    disable_events: multiball_firepower_started, game_ended
    reset_count_for_current_player_events: multiball_firepower_started

  firepower_lock_2:
    lock_devices: bd_lock2
    balls_to_lock: 1
    balls_to_replace: 1
    enable_events: qualify_lock_2
    disable_events: multiball_firepower_started, game_ended
    reset_count_for_current_player_events: multiball_firepower_started

  firepower_lock_3:
    lock_devices: bd_lock3
    balls_to_lock: 1
    balls_to_replace: 0
    enable_events: qualify_lock_3
    disable_events: multiball_firepower_started, game_ended
    reset_count_for_current_player_events: multiball_firepower_started

event_player:
  ball_started{current_player.lock_1_lit==1 and current_player.lock_1_held==0}:
    - qualify_lock_1
  ball_started{current_player.lock_2_lit==1 and current_player.lock_2_held==0}:
    - qualify_lock_2
  ball_started{current_player.lock_3_lit==1 and current_player.lock_3_held==0}:
    - qualify_lock_3
  ball_started{current_player.lock_1_lit==1 and current_player.lock_1_held==1}:
    - qualify_lock_1
  ball_started{current_player.lock_2_lit==1 and current_player.lock_2_held==1}:
    - qualify_lock_2
  ball_started{current_player.lock_3_lit==1 and current_player.lock_3_held==1}:
    - qualify_lock_3
  qualify_locks{current_player.lock_qualify_count==0}:
    - qualify_lock_1
    - qualify_lock_2
  qualify_locks{current_player.lock_qualify_count==1}:
    - qualify_lock_3
  qualify_locks{current_player.lock_qualify_count>=2 and current_player.lock_1_lit==0}:
    - qualify_lock_1
  qualify_locks{current_player.lock_qualify_count>=2 and current_player.lock_1_lit==1 and current_player.lock_2_lit==0}:
    - qualify_lock_2
  qualify_locks{current_player.lock_qualify_count>=2 and current_player.lock_1_lit==1 and current_player.lock_2_lit==1 and current_player.lock_3_lit==0}:
    - qualify_lock_3
  multiball_lock_firepower_lock_1_full{device.multiball_locks.firepower_lock_2.locked_balls==1 and device.multiball_locks.firepower_lock_3.locked_balls==1}:
    - start_firepower_multiball
  multiball_lock_firepower_lock_2_full{device.multiball_locks.firepower_lock_1.locked_balls==1 and device.multiball_locks.firepower_lock_3.locked_balls==1}:
    - start_firepower_multiball
  multiball_lock_firepower_lock_3_full{device.multiball_locks.firepower_lock_1.locked_balls==1 and device.multiball_locks.firepower_lock_2.locked_balls==1}:
    - start_firepower_multiball

show_player:
  qualify_lock_1:
    lock_1_ready_show:
      action: play
      loops: -1
  qualify_lock_2:
    lock_2_ready_show:
      action: play
      loops: -1
  qualify_lock_3:
    lock_3_ready_show:
      action: play
      loops: -1
  multiball_lock_firepower_lock_1_locked_ball:
    lock_1_ready_show:
      action: stop
    lock_1_locked_show:
      action: play
      loops: -1
  multiball_lock_firepower_lock_2_locked_ball:
    lock_2_ready_show:
      action: stop
    lock_2_locked_show:
      action: play
      loops: -1
  multiball_lock_firepower_lock_3_locked_ball:
    lock_3_ready_show:
      action: stop
    lock_3_locked_show:
      action: play
      loops: -1
  ball_started{current_player.lock_1_held==1}:
    lock_1_ready_show:
      action: stop
    lock_1_locked_show:
      action: play
      loops: -1
  ball_started{current_player.lock_2_held==1}:
    lock_2_ready_show:
      action: stop
    lock_2_locked_show:
      action: play
      loops: -1
  ball_started{current_player.lock_3_held==1}:
    lock_3_ready_show:
      action: stop
    lock_3_locked_show:
      action: play
      loops: -1

  multiball_firepower_started:
    lock_1_ready_show:
      action: stop
    lock_2_ready_show:
      action: stop
    lock_3_ready_show:
      action: stop
    lock_1_locked_show:
      action: stop
    lock_2_locked_show:
      action: stop
    lock_3_locked_show:
      action: stop

variable_player:
  ball_started{current_player.ball==1}:
    lock_qualify_count:
      int: 0
      action: set
    lock_1_lit:
      int: 0
      action: set
    lock_2_lit:
      int: 0
      action: set
    lock_3_lit:
      int: 0
      action: set
    lock_1_held:
      int: 0
      action: set
    lock_2_held:
      int: 0
      action: set
    lock_3_held:
      int: 0
      action: set

  qualify_locks:
    lock_qualify_count:
      int: 1
      action: add

  qualify_lock_1:
    lock_1_lit:
      int: 1
      action: set

  qualify_lock_2:
    lock_2_lit:
      int: 1
      action: set

  qualify_lock_3:
    lock_3_lit:
      int: 1
      action: set

  multiball_lock_firepower_lock_1_locked_ball:
    score: 9000
    lock_1_held:
      int: 1
      action: set

  multiball_lock_firepower_lock_2_locked_ball:
    score: 9000
    lock_2_held:
      int: 1
      action: set

  multiball_lock_firepower_lock_3_locked_ball:
    score: 9000
    lock_3_held:
      int: 1
      action: set

  multiball_firepower_started:
    lock_1_lit:
      int: 0
      action: set
    lock_2_lit:
      int: 0
      action: set
    lock_3_lit:
      int: 0
      action: set

  multiball_firepower_ended:
    lock_1_held:
      int: 0
      action: set
    lock_2_held:
      int: 0
      action: set
    lock_3_held:
      int: 0
      action: set
