#config_version=6
mode:
  start_events: game_started
  stop_events: game_ended
  priority: 100000

slide_player:
  _overwrite: true

segment_display_player:
  mode_player1_active_started:
    player1_display:
      action: add
      color: orange
      text: "{current_player.score}"
    player2_display:
      action: add
      color: orange
      text: ""
    player3_display:
      action: add
      color: orange
      text: ""
    player4_display:
      action: add
      color: orange
      text: ""
    credit_ball_display:
      action: add
      color: orange
      text: "{current_player.ball:d}"

# show score when adding players
  player_added{num==1}:
    player1_display:
      text: "{players[0].score:d}"
  player_added{num==2}:
    player2_display:
      text: "{players[1].score:d}"
  player_added{num==3}:
    player3_display:
      text: "{players[2].score:d}"
  player_added{num==4}:
    player4_display:
      text: "{players[3].score:d}"

# clear only display0 after game
  game_ended:
    credit_ball_display:
      text: ""                          # should show coins if not in freeplay
  game_ended{machine.player1_score > 0}:
    player1_display:
      text: "{machine.player1_score:d}"
  game_ended{machine.player2_score > 0}:
    player2_display:
      text: "{machine.player2_score:d}"
  game_ended{machine.player3_score > 0}:
    player3_display:
      text: "{machine.player3_score:d}"
  game_ended{machine.player4_score > 0}:
    player4_display:
      text: "{machine.player4_score:d}"

#flash display on player turn
  ball_starting{player==1}:
    player1_display:
      action: flash
  ball_starting{player==2}:
    player2_display:
      action: flash
  ball_starting{player==3}:
    player3_display:
      action: flash
  ball_starting{player==4}:
    player4_display:
      action: flash

  player_score:
    player1_display:
      action: no_flash
    player2_display:
      action: no_flash
    player3_display:
      action: no_flash
    player4_display:
      action: no_flash